drf_sp_hub/sp_api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from sp_api import views

app_name = 'sp_api'

router = DefaultRouter()
router.register(r'articles', views.ArticleViewSet)
router.register(r'conversations', views.ConversationViewSet)
router.register(r'keywords', views.SPKeywordViewSet, base_name='spkeyword')
router.register(r'categories', views.SPCategoryViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

drf_sp_hub/sp_app/urls.py
from django.conf.urls import url, include

from .views.conversation import ConversationList, ConversationAdd, ConversationEdit, ConversationDetail

app_name = 'sp_app'

conversation_patterns = [
    url(r'^$', ConversationList.as_view(), name='list_conversations'),
    url(r'^new$', ConversationAdd.as_view(), name='add_conversation'),
    url(r'^(?P<pk>.+)/$', ConversationDetail.as_view(), name='display_conversation'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_conversation'),
    url(r'^(?P<pk>.+)/edit$', ConversationEdit.as_view(), name='change_conversation'),
]

urlpatterns = [
    url(r'^conversations/', include(conversation_patterns)),
]

drf_sp_hub/sp_hub/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from allauth.account import views as allauth_views
from .views import homepage_view

app_name='sp_hub'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', allauth_views.LoginView.as_view(), name='login'),
    #    { 'template_name': 'core/login.html' },
    #    name='login'
    #),
    url(r'^logout/$', allauth_views.LogoutView.as_view(), { 'next_page': '/' }, name='logout'),
    url(r'^api/', include('sp_api.urls', namespace='sp_api')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('sp_app.urls', namespace='sp_app')),
    url(r'^', include('article.urls', namespace='article')),
    url(r'^', include('dossier.urls', namespace='dossier')),
    url(r'^', include('spkeyword.urls', namespace='spkeyword')),
    url(r'^$', homepage_view, name='home'),
]

drf_sp_hub/sp_app/models.py
from django.db import models
from django.conf import settings

from django.urls import reverse

from django.contrib.postgres.fields import JSONField

class Conversation(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT, null=True, blank=False, related_name='conversations')
    created_on = models.DateTimeField('published date', auto_now_add=True, blank=True)
    updated_on = models.DateTimeField('updated date', auto_now_add=True)

    articles = models.ManyToManyField('article.Article', blank=True, related_name='conversations')
    keywords = models.ManyToManyField('spkeyword.SPKeyword', blank=True, related_name='conversations')
    references = JSONField(null=True, blank=True)
    timeline = JSONField(null=False, blank=True)

    def get_absolute_url(self):
        return reverse('sp_app:display_conversation', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

drf_sp_hub/sp_app/forms.py
from django import forms

from .models import Conversation

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = [ 'title', 'articles', 'keywords',  ]
        hidden_fields = [ 'timeline', ]
        widgets = {
            'articles': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'}),
            'keywords': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'})
        }

drf_sp_hub/sp_app/views/article.py
from sp_app.models import Article
from sp_app.forms import ArticleForm

from lxml import etree

from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django import forms
from django.shortcuts import render
from sp_app.utils.zip_importer import ZipImporter

class ZipImportForm(forms.Form):
    zip_file = forms.FileField()

def import_zip_file(request):
    if request.method == 'POST':
        # Do something
        form = ZipImportForm(request.POST, request.FILES)
        if form.is_valid():
            zipimport = ZipImporter(request.FILES['zip_file'])
            form_msg = zipimport.process_files()
            zipimport.clean_files()
    else:
        form = ZipImportForm()
        form_msg = 'upload file'

    return render(request, 'articles/zipimport.html', { 'form': form, 'form_msg': form_msg })

drf_sp_hub/sp_app/views/category.py
from sp_app.models import SPCategory
from sp_app.forms import SPCategoryForm

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class CategoryList(ListView):
    model = SPCategory
    context_object_name = 'categories'
    template_name = 'categories/list_page.html'

class CategoryDetail(DetailView):
    model = SPCategory
    context_object_name = 'category'
    template_name = 'categories/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keywords = self.object.keywords.all()
        articles = []
        context['keywords'] = keywords
        for kw in keywords:
            articles.extend(kw.articles.all())
        context['articles'] = articles
        return context

class CategoryEdit(UpdateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

class CategoryAdd(CreateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

drf_sp_hub/sp_app/views/conversation.py
from sp_app.models import Conversation
from sp_app.forms import ConversationForm

import json

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class ConversationList(ListView):
    model = Conversation
    context_object_name = 'conversations'
    template_name = 'conversations/list_page.html'

class ConversationDetail(DetailView):
    model = Conversation
    fields = [ 'title', 'timeline' ]
    template_name = 'conversations/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['timeline'] = self.object.timeline
        return context

class ConversationEdit(UpdateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

class ConversationAdd(CreateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

drf_sp_hub/sp_app/templates/conversations/display.html
{% extends 'core/base.html' %}

{% load sp_tags %}

{% block content %}
<h2>{{ conversation }}</h2>
{% if perms.sp_api.change_conversation %}
  <a class="btn btn-warning btn-sm" href="{% url 'sp_app:change_conversation' conversation.pk %}">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
  </a>
{% endif %}
{% if perms.sp_api.delete_conversation %}
  <a class="btn btn-danger btn-sm" href="#">
    <i class="fa fa-trash-o" aria-hidden="true"></i> Delete
  </a>
{% endif %}
<h3>Articles</h3>
{% for article in conversation.articles.all %}
  <a href="{% url 'sp_app:display_article' article.pk %}" class="badge badge-light">{{ article }}</a>
{% endfor %}
<h3>Keywords</h3>
{% for keyword in conversation.keywords.all %}
  <a href="{% url 'sp_app:display_keyword' keyword.pk %}" class="badge badge-light">{{ keyword }}</a>
{% endfor %}
<h3>Timeline</h3>
{% for timestamp, value in conversation.timeline.items|dictsortreversed:0 %}
  <h6>{{ timestamp }} ({{ timestamp|parse_timestamp|date:'Y-m-d H:i:s' }}) {{ value }}</h6>
{% endfor %}
{% endblock %}

drf_sp_hub/sp_app/templates/conversations/edit.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}

{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function () {
//      $('.select-multi-keywords').select2();
      $('select.form-control').select2();
    });
  </script>
{% endblock %}

{% block content %}
    <h1>Edit conversation</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="save btn btn-success">Save</button>
        {% endbuttons %}
    </form>
{% endblock %}

drf_sp_hub/sp_app/templates/conversations/list.html
<h2>Liste de conversations</h2>
{% if perms.sp_api.add_conversation %}
  <a class="btn btn-success btn-sm" href="{% url 'sp_app:add_conversation' %}"><i class="fa fa-plus-square" aria-hidden="true"></i> Add</a>
{% endif %}
<div class="card-columns">
{% for conversation in conversations %}
  <div class="card"><div class="card-body">
    <h4 class="card-title">{{ conversation }}</a></h4>
    <p class="card-text">
      {% for kw in conversation.keywords.all %}
        <span class="badge badge-light">{{ kw }}</span>
      {% endfor %}
    </p>
    <a href="{% url 'sp_app:display_conversation' conversation.pk %}" class="card-link">Read more</a>
    <span class="card-link">ID {{ conversation.pk }}</span>
  </div></div>
{% endfor %}
</div>

drf_sp_hub/sp_app/templates/conversations/list_page.html
{% extends 'core/base.html' %}

{% block content %}
{% include 'conversations/list.html' %}
{% endblock %}