drf_sp_hub/article/urls.py
from django.conf.urls import url, include

from .views import ArticleList, ArticleAdd, ArticleDetail, ArticleEdit

app_name = 'article'

article_patterns = [
    url(r'^$', ArticleList.as_view(), name='list'),
    url(r'^new$', ArticleAdd.as_view(), name='add'),
    url(r'^(?P<pk>.+)/$', ArticleDetail.as_view(), name='display'),
    url(r'^(?P<pk>.+)/edit$', ArticleEdit.as_view(), name='edit'),
]

urlpatterns = [
    url(r'^articles/', include(article_patterns)),
]

drf_sp_hub/sp_api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from sp_api import views

app_name = 'sp_api'

router = DefaultRouter()
router.register(r'articles', views.ArticleViewSet)
router.register(r'conversations', views.ConversationViewSet)
router.register(r'keywords', views.SPKeywordViewSet, base_name='spkeyword')
router.register(r'categories', views.SPCategoryViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

drf_sp_hub/sp_app/urls.py
from django.conf.urls import url, include

from .views.conversation import ConversationList, ConversationAdd, ConversationEdit, ConversationDetail

app_name = 'sp_app'

conversation_patterns = [
    url(r'^$', ConversationList.as_view(), name='list_conversations'),
    url(r'^new$', ConversationAdd.as_view(), name='add_conversation'),
    url(r'^(?P<pk>.+)/$', ConversationDetail.as_view(), name='display_conversation'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_conversation'),
    url(r'^(?P<pk>.+)/edit$', ConversationEdit.as_view(), name='change_conversation'),
]

urlpatterns = [
    url(r'^conversations/', include(conversation_patterns)),
]

drf_sp_hub/sp_hub/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from allauth.account import views as allauth_views
from .views import homepage_view

app_name='sp_hub'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', allauth_views.LoginView.as_view(), name='login'),
    #    { 'template_name': 'core/login.html' },
    #    name='login'
    #),
    url(r'^logout/$', allauth_views.LogoutView.as_view(), { 'next_page': '/' }, name='logout'),
    url(r'^api/', include('sp_api.urls', namespace='sp_api')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('sp_app.urls', namespace='sp_app')),
    url(r'^', include('article.urls', namespace='article')),
    url(r'^', include('dossier.urls', namespace='dossier')),
    url(r'^', include('spkeyword.urls', namespace='spkeyword')),
    url(r'^$', homepage_view, name='home'),
]

drf_sp_hub/sp_api/models.py
import logging
from django.db import models
from django.conf import settings

from django.urls import reverse

from django.contrib.postgres.fields import JSONField

class SPCategory(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, db_index=True, unique=True)

    class Meta:
        verbose_name = "SP Category"
        verbose_name_plural = "SP Categories"

    def __str__(self):
        return self.name

class SPKeyword(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, db_index=True)
    language = models.CharField(max_length=3, null=False, blank=False, default='fr')
    translations = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)
    data = JSONField(null=True, blank=True)
    aligned = models.BooleanField(null=False, blank=False, default=False)
    is_editor = models.BooleanField(null=False, blank=False, default=False)
    category = models.ForeignKey(SPCategory, unique=False, related_name='keywords', db_index=True, null=True, blank=True, default=None, on_delete=models.SET_DEFAULT)

    class Meta:
        verbose_name = "SP Keyword"

    def get_absolute_url(self):
        return reverse('display_keyword', kwargs={'pk': self.pk})

    def __str__(self):
        if self.category:
            return self.name + ' (' + self.category.name + ')'
        else:
            return self.name


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT, related_name='articles', null=False, blank=False)
    created_on = models.DateTimeField('published date', auto_now_add=True, blank=True)

    # Not yet
    html_file = models.FileField(upload_to='tmp/', null=True, blank=True)
    basex_docid = models.CharField(max_length=200, null=True, blank=True)
    keywords = models.ManyToManyField(SPKeyword, related_name='articles', blank=True)

    def get_absolute_url(self):
        return reverse('display_article', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ' (ID ' + str(self.pk) + ')'

class Conversation(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT, null=True, blank=False, related_name='conversations')
    created_on = models.DateTimeField('published date', auto_now_add=True, blank=True)
    updated_on = models.DateTimeField('updated date', auto_now_add=True)

    articles = models.ManyToManyField(Article, blank=True, related_name='conversations')
    keywords = models.ManyToManyField(SPKeyword, blank=True, related_name='conversations')
    references = JSONField(null=True, blank=True)
    timeline = JSONField(null=False, blank=True)


    def __str__(self):
        return self.title + ' ' + str([ article.pk for article in self.articles.all() ])

drf_sp_hub/sp_app/models.py
from django.db import models
from django.conf import settings

from django.urls import reverse

from django.contrib.postgres.fields import JSONField

class Conversation(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT, null=True, blank=False, related_name='conversations')
    created_on = models.DateTimeField('published date', auto_now_add=True, blank=True)
    updated_on = models.DateTimeField('updated date', auto_now_add=True)

    articles = models.ManyToManyField('article.Article', blank=True, related_name='conversations')
    keywords = models.ManyToManyField('spkeyword.SPKeyword', blank=True, related_name='conversations')
    references = JSONField(null=True, blank=True)
    timeline = JSONField(null=False, blank=True)

    def get_absolute_url(self):
        return reverse('sp_app:display_conversation', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

drf_sp_hub/sp_app/forms.py
from django import forms

from .models import Conversation

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = [ 'title', 'articles', 'keywords',  ]
        hidden_fields = [ 'timeline', ]
        widgets = {
            'articles': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'}),
            'keywords': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'})
        }

drf_sp_hub/sp_app/views/article.py
from sp_app.models import Article
from sp_app.forms import ArticleForm

from lxml import etree

from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django import forms
from django.shortcuts import render
from sp_app.utils.zip_importer import ZipImporter

class ZipImportForm(forms.Form):
    zip_file = forms.FileField()

def import_zip_file(request):
    if request.method == 'POST':
        # Do something
        form = ZipImportForm(request.POST, request.FILES)
        if form.is_valid():
            zipimport = ZipImporter(request.FILES['zip_file'])
            form_msg = zipimport.process_files()
            zipimport.clean_files()
    else:
        form = ZipImportForm()
        form_msg = 'upload file'

    return render(request, 'articles/zipimport.html', { 'form': form, 'form_msg': form_msg })

drf_sp_hub/sp_app/views/category.py
from sp_app.models import SPCategory
from sp_app.forms import SPCategoryForm

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class CategoryList(ListView):
    model = SPCategory
    context_object_name = 'categories'
    template_name = 'categories/list_page.html'

class CategoryDetail(DetailView):
    model = SPCategory
    context_object_name = 'category'
    template_name = 'categories/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keywords = self.object.keywords.all()
        articles = []
        context['keywords'] = keywords
        for kw in keywords:
            articles.extend(kw.articles.all())
        context['articles'] = articles
        return context

class CategoryEdit(UpdateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

class CategoryAdd(CreateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

drf_sp_hub/sp_app/views/conversation.py
from sp_app.models import Conversation
from sp_app.forms import ConversationForm

import json

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class ConversationList(ListView):
    model = Conversation
    context_object_name = 'conversations'
    template_name = 'conversations/list_page.html'

class ConversationDetail(DetailView):
    model = Conversation
    fields = [ 'title', 'timeline' ]
    template_name = 'conversations/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['timeline'] = self.object.timeline
        return context

class ConversationEdit(UpdateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

class ConversationAdd(CreateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

drf_sp_hub/sp_app/templates/keywords/display.html
{% extends 'core/base.html' %}

{% block content %}
<h2>{{ keyword.name }}</h2>
{% if perms.sp_api.change_spkeyword %}
  <a class="btn btn-warning btn-sm" href="{% url 'spkeyword:edit' keyword.pk %}">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
  </a>
{% endif %}
<dl class="row">
  {% if keyword.category %}
    <dt class="col-3">Category</dt>
    <dd class="col-9">{{ keyword.category.name }}</dd>
  {% endif %}
  {% for source, reference in keyword.data.items %}
    <dt class="col-3">{{ source }}</dt>
    <dd class="col-9">{{ reference }}</dd>
  {% endfor %}
  <dt class="col-3">Language</dt>
  <dd class="col-9">{{ keyword.language }}</dd>
  {% if keyword.is_translation.pk %}
    <dt class="col-3">Translation of</dt>
    <dd class="col-9"><a href="{% url 'spkeyword:display' keyword.is_translation.pk %}">
      {{ keyword.is_translation}}
    </a></dd>
  {% else %}
    {% for t in keyword.translations.all %}
      <dt class="col-3">Translation ({{ t.language }})</dt>
      <dd class="col-9"><a href="{% url 'spkeyword:display' t.pk %}">{{ t.name }}</a></dd>
    {% endfor %}
  {% endif %}
</dl>
<h3>Tagged articles</h3>
  <ul>
  {% for article in keyword.articles.all %}
    <li><a href="{% url 'article:display' article.pk %}">{{ article }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}

drf_sp_hub/sp_app/templates/keywords/edit.html
{% extends 'core/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
  <script src="{% static "js/edit_keywords.js" %}"></script>
{% endblock %}

{% block content %}
    <h1>Edit tag</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form exclude="data" %}
        {{ form.data.as_hidden }}
        {% buttons %}
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addAlignmentModal">
            Add alignment
          </button>
          <button type="submit" class="save btn btn-success">Save</button>
        {% endbuttons %}
    </form>

    <!-- Modal -->
    <div class="modal fade" id="addAlignmentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input type="text" value="newLabel" id="newLabel">
        <input type="text" value="newValue" id="newValue">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="addLineSaveBtn">Save changes</button>
      </div>
    </div>
    </div>
    </div>
{% endblock %}

drf_sp_hub/sp_app/templates/keywords/list.html
<h2>Liste de mots-clés</h2>
<table id="keywordsTable" class="table">
  <thead>
    <tr>
      <td>ID</td>
      <td>Nom</td>
      <td>Catégorie</td>
      <td>Auteur | éditeur</td>
      <td>Aligné</td>
    </tr>
  </thead>
  <tbody>
    {% for item in keywords %}
    <tr>
      <td>{{ item.pk }}</td>
      <td><a href="{% url 'spkeyword:display' item.pk %}">{{ item.name }}</a></td>
      <td>{{ item.category }}</td>
      <td>{{ item.is_editor }}</td>
      <td>{{ item.aligned }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

drf_sp_hub/sp_app/templates/keywords/list_page.html
{% extends 'core/base.html' %}

{% block content %}
{% include 'keywords/list.html' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css">
{% endblock %}

{% block js %}
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#keywordsTable').DataTable({
      "pageLength": 50,
      responsive: true,
    });
} );
</script>
{% endblock %}