drf_sp_hub/sp_api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from sp_api import views

app_name = 'sp_api'

router = DefaultRouter()
router.register(r'articles', views.ArticleViewSet)
router.register(r'conversations', views.ConversationViewSet)
router.register(r'keywords', views.SPKeywordViewSet, base_name='spkeyword')
router.register(r'categories', views.SPCategoryViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

drf_sp_hub/sp_app/urls.py
from django.conf.urls import url, include

from .views.conversation import ConversationList, ConversationAdd, ConversationEdit, ConversationDetail

app_name = 'sp_app'

conversation_patterns = [
    url(r'^$', ConversationList.as_view(), name='list_conversations'),
    url(r'^new$', ConversationAdd.as_view(), name='add_conversation'),
    url(r'^(?P<pk>.+)/$', ConversationDetail.as_view(), name='display_conversation'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_conversation'),
    url(r'^(?P<pk>.+)/edit$', ConversationEdit.as_view(), name='change_conversation'),
]

urlpatterns = [
    url(r'^conversations/', include(conversation_patterns)),
]

drf_sp_hub/sp_hub/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from allauth.account import views as allauth_views
from .views import homepage_view

app_name='sp_hub'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', allauth_views.LoginView.as_view(), name='login'),
    #    { 'template_name': 'core/login.html' },
    #    name='login'
    #),
    url(r'^logout/$', allauth_views.LogoutView.as_view(), { 'next_page': '/' }, name='logout'),
    url(r'^api/', include('sp_api.urls', namespace='sp_api')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('sp_app.urls', namespace='sp_app')),
    url(r'^', include('article.urls', namespace='article')),
    url(r'^', include('dossier.urls', namespace='dossier')),
    url(r'^', include('spkeyword.urls', namespace='spkeyword')),
    url(r'^$', homepage_view, name='home'),
]

drf_sp_hub/spkeyword/urls.py
from django.conf.urls import url, include

from .views import KeywordList, KeywordAdd, KeywordEdit, KeywordDetail
from .views import CategoryList, CategoryAdd, CategoryEdit, CategoryDetail

app_name = 'spkeyword'

keyword_patterns = [
    url(r'^$', KeywordList.as_view(), name='list'),
    url(r'^new$', KeywordAdd.as_view(), name='add'),
    url(r'^(?P<pk>.+)/$', KeywordDetail.as_view(), name='display'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_keyword'),
    url(r'^(?P<pk>.+)/edit$', KeywordEdit.as_view(), name='edit'),
]

category_patterns = [
    url(r'^$', CategoryList.as_view(), name='list_categories'),
    url(r'^new$', CategoryAdd.as_view(), name='add_category'),
    url(r'^(?P<pk>.+)/$', CategoryDetail.as_view(), name='display_category'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_category'),
    url(r'^(?P<pk>.+)/edit$', CategoryEdit.as_view(), name='edit_category'),
]

urlpatterns = [
    url(r'^keywords/', include(keyword_patterns)),
    url(r'^categories/', include(category_patterns)),
]

drf_sp_hub/templates/core/navigation.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark"><div class="container">
  <a class="navbar-brand" href="#">SP Hub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sp_app:list_articles' %}">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sp_app:list_categories' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sp_app:list_keywords' %}">Keywords</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sp_app:list_conversations' %}">Conversations</a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item"><a class="nav-link" href="{% url 'sp_api:api-root' %}">API REST</a></li>
      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Utilities
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'admin:index' %}">Django admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</div></nav>