drf_sp_hub/article/urls.py
from django.conf.urls import url, include

from .views import ArticleList, ArticleAdd, ArticleDetail, ArticleEdit

app_name = 'article'

article_patterns = [
    url(r'^$', ArticleList.as_view(), name='list'),
    url(r'^new$', ArticleAdd.as_view(), name='add'),
    url(r'^(?P<pk>.+)/$', ArticleDetail.as_view(), name='display'),
    url(r'^(?P<pk>.+)/edit$', ArticleEdit.as_view(), name='edit'),
]

urlpatterns = [
    url(r'^articles/', include(article_patterns)),
]

drf_sp_hub/sp_api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from sp_api import views

app_name = 'sp_api'

router = DefaultRouter()
router.register(r'articles', views.ArticleViewSet)
router.register(r'conversations', views.ConversationViewSet)
router.register(r'keywords', views.SPKeywordViewSet, base_name='spkeyword')
router.register(r'categories', views.SPCategoryViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]

drf_sp_hub/sp_app/urls.py
from django.conf.urls import url, include

from .views.conversation import ConversationList, ConversationAdd, ConversationEdit, ConversationDetail

app_name = 'sp_app'

conversation_patterns = [
    url(r'^$', ConversationList.as_view(), name='list_conversations'),
    url(r'^new$', ConversationAdd.as_view(), name='add_conversation'),
    url(r'^(?P<pk>.+)/$', ConversationDetail.as_view(), name='display_conversation'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_conversation'),
    url(r'^(?P<pk>.+)/edit$', ConversationEdit.as_view(), name='change_conversation'),
]

urlpatterns = [
    url(r'^conversations/', include(conversation_patterns)),
]

drf_sp_hub/sp_hub/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
from allauth.account import views as allauth_views
from .views import homepage_view

app_name='sp_hub'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', allauth_views.LoginView.as_view(), name='login'),
    #    { 'template_name': 'core/login.html' },
    #    name='login'
    #),
    url(r'^logout/$', allauth_views.LogoutView.as_view(), { 'next_page': '/' }, name='logout'),
    url(r'^api/', include('sp_api.urls', namespace='sp_api')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('sp_app.urls', namespace='sp_app')),
    url(r'^', include('article.urls', namespace='article')),
    url(r'^', include('dossier.urls', namespace='dossier')),
    url(r'^', include('spkeyword.urls', namespace='spkeyword')),
    url(r'^$', homepage_view, name='home'),
]

drf_sp_hub/spkeyword/urls.py
from django.conf.urls import url, include

from .views import KeywordList, KeywordAdd, KeywordEdit, KeywordDetail
from .views import CategoryList, CategoryAdd, CategoryEdit, CategoryDetail

app_name = 'spkeyword'

keyword_patterns = [
    url(r'^$', KeywordList.as_view(), name='list'),
    url(r'^new$', KeywordAdd.as_view(), name='add'),
    url(r'^(?P<pk>.+)/$', KeywordDetail.as_view(), name='display'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_keyword'),
    url(r'^(?P<pk>.+)/edit$', KeywordEdit.as_view(), name='edit'),
]

category_patterns = [
    url(r'^$', CategoryList.as_view(), name='list_categories'),
    url(r'^new$', CategoryAdd.as_view(), name='add_category'),
    url(r'^(?P<pk>.+)/$', CategoryDetail.as_view(), name='display_category'),
#    url(r'^(?P<pk>.+)/edit$', add_change_spkeyword, name='change_category'),
    url(r'^(?P<pk>.+)/edit$', CategoryEdit.as_view(), name='edit_category'),
]

urlpatterns = [
    url(r'^keywords/', include(keyword_patterns)),
    url(r'^categories/', include(category_patterns)),
]

drf_sp_hub/sp_app/models.py
from django.db import models
from django.conf import settings

from django.urls import reverse

from django.contrib.postgres.fields import JSONField

class Conversation(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT, null=True, blank=False, related_name='conversations')
    created_on = models.DateTimeField('published date', auto_now_add=True, blank=True)
    updated_on = models.DateTimeField('updated date', auto_now_add=True)

    articles = models.ManyToManyField('article.Article', blank=True, related_name='conversations')
    keywords = models.ManyToManyField('spkeyword.SPKeyword', blank=True, related_name='conversations')
    references = JSONField(null=True, blank=True)
    timeline = JSONField(null=False, blank=True)

    def get_absolute_url(self):
        return reverse('sp_app:display_conversation', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

drf_sp_hub/sp_app/forms.py
from django import forms

from .models import Conversation

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = [ 'title', 'articles', 'keywords',  ]
        hidden_fields = [ 'timeline', ]
        widgets = {
            'articles': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'}),
            'keywords': forms.SelectMultiple(attrs={'class': 'select-multi-keywords, form-control'})
        }

drf_sp_hub/sp_app/views/article.py
from sp_app.models import Article
from sp_app.forms import ArticleForm

from lxml import etree

from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django import forms
from django.shortcuts import render
from sp_app.utils.zip_importer import ZipImporter

class ZipImportForm(forms.Form):
    zip_file = forms.FileField()

def import_zip_file(request):
    if request.method == 'POST':
        # Do something
        form = ZipImportForm(request.POST, request.FILES)
        if form.is_valid():
            zipimport = ZipImporter(request.FILES['zip_file'])
            form_msg = zipimport.process_files()
            zipimport.clean_files()
    else:
        form = ZipImportForm()
        form_msg = 'upload file'

    return render(request, 'articles/zipimport.html', { 'form': form, 'form_msg': form_msg })

drf_sp_hub/sp_app/views/category.py
from sp_app.models import SPCategory
from sp_app.forms import SPCategoryForm

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class CategoryList(ListView):
    model = SPCategory
    context_object_name = 'categories'
    template_name = 'categories/list_page.html'

class CategoryDetail(DetailView):
    model = SPCategory
    context_object_name = 'category'
    template_name = 'categories/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        keywords = self.object.keywords.all()
        articles = []
        context['keywords'] = keywords
        for kw in keywords:
            articles.extend(kw.articles.all())
        context['articles'] = articles
        return context

class CategoryEdit(UpdateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

class CategoryAdd(CreateView):
    model = SPCategory
    form_class = SPCategoryForm
    template_name = 'categories/edit.html'

drf_sp_hub/sp_app/views/conversation.py
from sp_app.models import Conversation
from sp_app.forms import ConversationForm

import json

from django.views.generic import ListView, DetailView, CreateView, UpdateView

class ConversationList(ListView):
    model = Conversation
    context_object_name = 'conversations'
    template_name = 'conversations/list_page.html'

class ConversationDetail(DetailView):
    model = Conversation
    fields = [ 'title', 'timeline' ]
    template_name = 'conversations/display.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['timeline'] = self.object.timeline
        return context

class ConversationEdit(UpdateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

class ConversationAdd(CreateView):
    model = Conversation
    form_class = ConversationForm
    template_name = 'conversations/edit.html'

drf_sp_hub/sp_app/templates/core/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  {% block extra_head %}
  {% endblock %}

  <title>Sens Public</title>
  <meta name="description" content="Sens Public v2">
  <meta name="author" content="Tim">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% bootstrap_css %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/style.css" %}">

  {% block css %}
  {% endblock %}
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
  {% include "core/navigation.html" %}
  <main role="main" class="container">
    {% block content %}
    {% endblock %}
  </main>
  <script type="text/javascript" src="//code.jquery.com/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="{% static "js/core.js" %}"></script>
  {% bootstrap_javascript %}
  {% block js %}
  {% endblock %}
</body>
</html>

drf_sp_hub/sp_app/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
{% endblock %}

drf_sp_hub/sp_app/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

drf_sp_hub/sp_app/templates/core/navigation.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark"><div class="container">
  <a class="navbar-brand" href="#">SP Hub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'article:list' %}">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'spkeyword:list_categories' %}">Categories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'spkeyword:list' %}">Keywords</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dossier:list' %}">Dossiers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'sp_app:list_conversations' %}">Conversations</a>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item"><a class="nav-link" href="{% url 'sp_api:api-root' %}">API REST</a></li>
      {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Utilities
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'admin:index' %}">Django admin</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
        </li>
      {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</div></nav>